USE [empresa_prueba_ud3]
GO

/****** Object:  Table [dbo].[ACC_MOVEMENT]    Script Date: 19/03/2023 13:05:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'dbo.ACC_MOVEMENT', N'U') IS  NULL
BEGIN
	CREATE TABLE [dbo].[ACC_MOVEMENT](
		[ACCOUNT_MOV_ID] [int] IDENTITY(1,1) NOT NULL,
		[ACCOUNT_ORIGIN_ID] [int] NOT NULL,
		[ACCOUNT_DEST_ID] [int] NOT NULL,
		[AMOUNT] [money] NOT NULL,
		[DATETIME] [datetime] NOT NULL,
	 CONSTRAINT [PK_ACC_MOVEMENT] PRIMARY KEY CLUSTERED 
	(
		[ACCOUNT_MOV_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 19/03/2023 13:05:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'dbo.ACCOUNT', N'U') IS  NULL
BEGIN
	CREATE TABLE [dbo].[ACCOUNT](
		[ACCOUNTNO] [int] IDENTITY(1,1) NOT NULL,
		[AMOUNT] [money] NOT NULL,
	 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
	(
		[ACCOUNTNO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 19/03/2023 13:05:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'dbo.DEPARTMENT', N'U') IS  NULL
BEGIN
	CREATE TABLE [dbo].[DEPARTMENT](
		[DEPTNO] [int] IDENTITY(1,1) NOT NULL,
		[DNAME] [varchar](20) NULL,
		[LOC] [varchar](20) NULL,
	PRIMARY KEY CLUSTERED 
	(
		[DEPTNO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 19/03/2023 13:05:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'dbo.EMPLOYEE', N'U') IS  NULL
BEGIN
	CREATE TABLE [dbo].[EMPLOYEE](
		[EMPLOYEENO] [int] IDENTITY(1,1) NOT NULL,
		[ENAME] [varchar](20) NULL,
		[JOB] [varchar](20) NULL,
		[MGR] [int] NULL,
		[HIREDATE] [date] NULL,
		[SAL] [money] NULL,
		[COMM] [money] NULL,
		[DEPARTMENTNO] [int] NULL,
	PRIMARY KEY CLUSTERED 
	(
		[EMPLOYEENO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
/****** Object:  Table [dbo].[EMPLOYEE_ACCOUNT]    Script Date: 19/03/2023 13:05:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'dbo.EMPLOYEE_ACCOUNT', N'U') IS  NULL
BEGIN
	CREATE TABLE [dbo].[EMPLOYEE_ACCOUNT](
		[EMPLOYEENO] [int] NOT NULL,
		[ACCOUNTNO] [int] NOT NULL,
	 CONSTRAINT [PK_EMPLOYEE_ACCOUNT] PRIMARY KEY CLUSTERED 
	(
		[EMPLOYEENO] ASC,
		[ACCOUNTNO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END




