USE empresa_prueba_ud3
GO

ALTER TABLE [dbo].[ACC_MOVEMENT]  WITH CHECK ADD  CONSTRAINT [FK_ACC_MOVEMENT_ACCOUNT_DEST] FOREIGN KEY([ACCOUNT_DEST_ID])
REFERENCES [dbo].[ACCOUNT] ([ACCOUNTNO])
GO
ALTER TABLE [dbo].[ACC_MOVEMENT] CHECK CONSTRAINT [FK_ACC_MOVEMENT_ACCOUNT_DEST]
GO
ALTER TABLE [dbo].[ACC_MOVEMENT]  WITH CHECK ADD  CONSTRAINT [FK_ACC_MOVEMENT_ACCOUNT_ORIGIN] FOREIGN KEY([ACCOUNT_ORIGIN_ID])
REFERENCES [dbo].[ACCOUNT] ([ACCOUNTNO])
GO
ALTER TABLE [dbo].[ACC_MOVEMENT] CHECK CONSTRAINT [FK_ACC_MOVEMENT_ACCOUNT_ORIGIN]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([DEPARTMENTNO])
REFERENCES [dbo].[DEPARTMENT] ([DEPTNO])
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([MGR])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEENO])
GO
ALTER TABLE [dbo].[EMPLOYEE_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_ACCOUNT_ACCOUNT] FOREIGN KEY([ACCOUNTNO])
REFERENCES [dbo].[ACCOUNT] ([ACCOUNTNO])
GO
ALTER TABLE [dbo].[EMPLOYEE_ACCOUNT] CHECK CONSTRAINT [FK_EMPLOYEE_ACCOUNT_ACCOUNT]
GO
ALTER TABLE [dbo].[EMPLOYEE_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_ACCOUNT_EMPLOYEE] FOREIGN KEY([EMPLOYEENO])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEENO])
GO
ALTER TABLE [dbo].[EMPLOYEE_ACCOUNT] CHECK CONSTRAINT [FK_EMPLOYEE_ACCOUNT_EMPLOYEE]
GO
